name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev meson ninja-build pkg-config

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build binary
        run: cargo build --release

      - name: Package release artifact
        run: |
          mkdir -p dist/package/examples
          cp target/release/codex-waybar dist/package/
          cp README.md dist/package/
          cp -r examples/. dist/package/examples/
          mkdir -p dist/package/systemd
          cp systemd/codex-waybar.service dist/package/systemd/
          tar -czf dist/codex-waybar-x86_64-unknown-linux-gnu.tar.gz -C dist/package .

      - name: Publish release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/codex-waybar-x86_64-unknown-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
